"""Add order_id to Cart model

Revision ID: f5e6dbd8cd3e
Revises: 2ff5a31ae6ca
Create Date: 2024-08-11 13:55:26.807727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e6dbd8cd3e'
down_revision = '2ff5a31ae6ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'order_id')
    # ### end Alembic commands ###
